### ISSUE TITLE
Contrast mapping example fails because of dimension mismatch

### ISSUE THREAD

**Issue by madhur4127** [PBibiloni/softcolor#2]
`examples/example_contrast_mapping.py` throws the error: 

```
Traceback (most recent call last):
  File "example_contrast_mapping.py", line 24, in <module>
    num_iterations=3)
  File "../softcolor/morphology.py", line 119, in contrast_mapping_with_steps
    structuring_element=structuring_element)
  File "../softcolor/morphology.py", line 150, in dilation
    lab_image = _rgb_to_lab(image_as_rgb)/100.0
  File "../softcolor/morphology.py", line 169, in _rgb_to_lab
    lab_flat[nonnan_mask, :, :] = color.rgb2lab(rgb_flat[nonnan_mask, :, :])
  File "/usr/local/lib/python3.6/dist-packages/skimage/color/colorconv.py", line 1032, in rgb2lab
    return xyz2lab(rgb2xyz(rgb), illuminant, observer)
  File "/usr/local/lib/python3.6/dist-packages/skimage/color/colorconv.py", line 674, in rgb2xyz
    arr = _prepare_colorarray(rgb).copy()
  File "/usr/local/lib/python3.6/dist-packages/skimage/color/colorconv.py", line 145, in _prepare_colorarray
    raise ValueError(msg)
ValueError: the input array must be have a shape == (.., ..,[ ..,] 3)), got (10000, 1, 4)

```

**Comment by madhur4127** [comment]
Other examples like `example_erosion_dilation.py`, `example_opening_closing.py` fails with the same error.
